### ISSUE TITLE
Human Classification of Table Types

### ISSUE THREAD

**Issue by petermr** [ContentMine/cm-ucl#13]
This issue will track our development of Table Types. Please contribute your thoughts by replying to this issue and keep the theme restricted to Development of Table Types.

For each Pubstyle we will assign a TableType. This will be iterative as we discover (a) the totality of types and (b) consistency within a PubStyle. 

The actual PubStyles should be included in a subdirectory of PubStyles and this Issue used to discuss problems in assigning PubStyles.

**Example**
(This is NOT final!)
```
pubstyle: BMJ
style: APA-like
  separator: full hruler
title:
  title-regex:"Title \\d+\\s"
  title-weight: bold
  title-wrap: yes
  title-wrap-indent: none
title-caption:
  caption-weight: bold
header:
  header-weight: bold
  header-separator: spanning-hruler
  header-wrap: yes
  header-wrap-indent: 8 px
body:
  weight: normal
  row-separator: none
  body-row:
    cell-separator: whitespace
    cell-cell-distance-min : 20 px
  subtable:
    indent: yes
```
and so on. Suggest that we can find some CSS terms for this.
